<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Interp</title>
    <script src="<?= WEB_ROOT ?>/public/js/String.js"></script>
    <script src="<?= WEB_ROOT ?>/public/js/$element/$element.js"></script>
    <script src="<?= WEB_ROOT ?>/public/js/$element/$elementsCollection.js"></script>
    <script src="<?= WEB_ROOT ?>/public/js/Component.js"></script>
    <script src="<?= WEB_ROOT ?>/public/js/utilities.js"></script>

    <script src="<?= WEB_ROOT ?>/public/js/repositories/Film.js"></script>
    <script src="<?= WEB_ROOT ?>/public/js/views/FilmViews.js"></script>
    <script src="<?= WEB_ROOT ?>/public/js/controllers/FilmController.js"></script>
</head>

<body>
    <?php dump('hi'); ?>
    <div id="app"></div>
    <script src="<?= WEB_ROOT ?>/public/js/app.js"></script>
</body>

</html>